const companySelectionData = [
  { companyId: 61, selectionCount: 15 },
  { companyId: 62, selectionCount: 22 },
  { companyId: 63, selectionCount: 18 },
  { companyId: 64, selectionCount: 10 },
  { companyId: 65, selectionCount: 25 },
  { companyId: 66, selectionCount: 12 },
  { companyId: 67, selectionCount: 30 },
  { companyId: 68, selectionCount: 8 },
  { companyId: 69, selectionCount: 20 },
  { companyId: 70, selectionCount: 17 },
  { companyId: 71, selectionCount: 14 },
  { companyId: 72, selectionCount: 9 },
  { companyId: 73, selectionCount: 11 },
  { companyId: 74, selectionCount: 13 },
  { companyId: 75, selectionCount: 19 },
  { companyId: 76, selectionCount: 23 },
  { companyId: 77, selectionCount: 16 },
  { companyId: 78, selectionCount: 21 },
  { companyId: 79, selectionCount: 26 },
  { companyId: 80, selectionCount: 7 },
  { companyId: 81, selectionCount: 28 },
  { companyId: 82, selectionCount: 5 },
  { companyId: 83, selectionCount: 6 },
  { companyId: 84, selectionCount: 13 },
  { companyId: 85, selectionCount: 20 },
  { companyId: 86, selectionCount: 12 },
  { companyId: 87, selectionCount: 18 },
  { companyId: 88, selectionCount: 14 },
  { companyId: 89, selectionCount: 17 },
  { companyId: 90, selectionCount: 11 },
];

export default companySelectionData;
