const companySelectionData = [
  { companyId: 10, selectionCount: 15 },
  { companyId: 11, selectionCount: 22 },
  { companyId: 12, selectionCount: 18 },
  { companyId: 13, selectionCount: 10 },
  { companyId: 14, selectionCount: 25 },
  { companyId: 15, selectionCount: 12 },
  { companyId: 16, selectionCount: 30 },
  { companyId: 17, selectionCount: 8 },
  { companyId: 18, selectionCount: 20 },
  { companyId: 19, selectionCount: 17 },
  { companyId: 20, selectionCount: 14 },
  { companyId: 21, selectionCount: 9 },
  { companyId: 22, selectionCount: 11 },
  { companyId: 23, selectionCount: 13 },
  { companyId: 24, selectionCount: 19 },
  { companyId: 25, selectionCount: 23 },
  { companyId: 26, selectionCount: 16 },
  { companyId: 27, selectionCount: 21 },
  { companyId: 28, selectionCount: 26 },
  { companyId: 29, selectionCount: 7 },
  { companyId: 30, selectionCount: 28 },
  { companyId: 31, selectionCount: 5 },
  { companyId: 32, selectionCount: 6 },
  { companyId: 33, selectionCount: 13 },
  { companyId: 34, selectionCount: 20 },
  { companyId: 35, selectionCount: 12 },
  { companyId: 36, selectionCount: 18 },
  { companyId: 37, selectionCount: 14 },
  { companyId: 38, selectionCount: 17 },
  { companyId: 39, selectionCount: 11 },
  { companyId: 40, selectionCount: 19 },
];

export default companySelectionData;
